"""device and devicetype

Revision ID: 080b9ae7ddee
Revises: 38318c1bc6f8
Create Date: 2025-07-01 16:00:58.579398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080b9ae7ddee'
down_revision: Union[str, None] = '38318c1bc6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicetype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hw_version', sa.String(length=50), nullable=True),
    sa.Column('sw_version', sa.String(length=50), nullable=True),
    sa.Column('sw_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('device', sa.Column('devicetype_id', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('retail_markup', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'device', 'devicetype', ['devicetype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'retail_markup')
    op.drop_column('device', 'devicetype_id')
    op.drop_table('devicetype')
    # ### end Alembic commands ###
