"""create many tables

Revision ID: 0d662679cfa0
Revises: 65dbad14a534
Create Date: 2025-05-16 19:32:23.272566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d662679cfa0'
down_revision: Union[str, None] = '65dbad14a534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargeowner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('glnnumber', sa.String(length=15), nullable=True),
    sa.Column('company', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=150), nullable=True),
    sa.Column('chargetype', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spotprice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('HourUTC', sa.DateTime(), nullable=False),
    sa.Column('HourDK', sa.DateTime(), nullable=False),
    sa.Column('DateDK', sa.DateTime(), nullable=False),
    sa.Column('PriceArea', sa.String(length=15), nullable=False),
    sa.Column('SpotpriceDKK', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotprice_DateDK'), 'spotprice', ['DateDK'], unique=False)
    op.create_index(op.f('ix_spotprice_PriceArea'), 'spotprice', ['PriceArea'], unique=False)
    op.create_table('tarif',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('nettarif', sa.Float(), nullable=True),
    sa.Column('systemtarif', sa.Float(), nullable=True),
    sa.Column('includingVAT', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('taxammount', sa.Float(), nullable=True),
    sa.Column('includingVAT', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chargeowner_id', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.String(length=15), nullable=True),
    sa.Column('charge_type_code', sa.String(length=15), nullable=True),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('price1', sa.Float(), nullable=True),
    sa.Column('price2', sa.Float(), nullable=True),
    sa.Column('price3', sa.Float(), nullable=True),
    sa.Column('price4', sa.Float(), nullable=True),
    sa.Column('price5', sa.Float(), nullable=True),
    sa.Column('price6', sa.Float(), nullable=True),
    sa.Column('price7', sa.Float(), nullable=True),
    sa.Column('price8', sa.Float(), nullable=True),
    sa.Column('price9', sa.Float(), nullable=True),
    sa.Column('price10', sa.Float(), nullable=True),
    sa.Column('price11', sa.Float(), nullable=True),
    sa.Column('price12', sa.Float(), nullable=True),
    sa.Column('price13', sa.Float(), nullable=True),
    sa.Column('price14', sa.Float(), nullable=True),
    sa.Column('price15', sa.Float(), nullable=True),
    sa.Column('price16', sa.Float(), nullable=True),
    sa.Column('price17', sa.Float(), nullable=True),
    sa.Column('price18', sa.Float(), nullable=True),
    sa.Column('price19', sa.Float(), nullable=True),
    sa.Column('price20', sa.Float(), nullable=True),
    sa.Column('price21', sa.Float(), nullable=True),
    sa.Column('price22', sa.Float(), nullable=True),
    sa.Column('price23', sa.Float(), nullable=True),
    sa.Column('price24', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chargeowner_id'], ['chargeowner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('chargeowner_id', sa.Integer(), nullable=True),
    sa.Column('PriceArea', sa.String(length=15), nullable=True),
    sa.Column('Config', sa.String(length=1000), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chargeowner_id'], ['chargeowner.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('charge')
    op.drop_table('tax')
    op.drop_table('tarif')
    op.drop_index(op.f('ix_spotprice_PriceArea'), table_name='spotprice')
    op.drop_index(op.f('ix_spotprice_DateDK'), table_name='spotprice')
    op.drop_table('spotprice')
    op.drop_table('chargeowner')
    # ### end Alembic commands ###
