"""update charge_chargeowner

Revision ID: 0f983b90d246
Revises: 8cd5709a7f8c
Create Date: 2025-05-21 18:59:01.803614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f983b90d246'
down_revision: Union[str, None] = '8cd5709a7f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeowner', sa.Column('compagny', sa.String(length=15), nullable=True))
    op.add_column('chargeowner', sa.Column('chargetypecode', sa.String(length=150), nullable=True))
    op.alter_column('chargeowner', 'chargetype',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_column('chargeowner', 'company')
    op.drop_column('chargeowner', 'name')
    op.drop_column('chargeowner', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeowner', sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('chargeowner', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('chargeowner', sa.Column('company', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.alter_column('chargeowner', 'chargetype',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('chargeowner', 'chargetypecode')
    op.drop_column('chargeowner', 'compagny')
    # ### end Alembic commands ###
