"""firmwareupdate 1

Revision ID: 219ac7502bf2
Revises: 9c6c2fcc18d6
Create Date: 2025-07-05 17:50:01.980644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219ac7502bf2'
down_revision: Union[str, None] = '9c6c2fcc18d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devicetype_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('repo_url', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devicetype_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('device', sa.Column('firmware_id', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('hardware_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'firmware', ['firmware_id'], ['id'])
    op.create_foreign_key(None, 'device', 'hardware', ['hardware_id'], ['id'])
    op.add_column('devicetype', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('devicetype', sa.Column('created_at', sa.Date(), nullable=False))
    op.drop_column('devicetype', 'sw_version')
    op.drop_column('devicetype', 'sw_date')
    op.drop_column('devicetype', 'hw_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicetype', sa.Column('hw_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('devicetype', sa.Column('sw_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('devicetype', sa.Column('sw_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('devicetype', 'created_at')
    op.drop_column('devicetype', 'description')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'hardware_id')
    op.drop_column('device', 'firmware_id')
    op.drop_table('hardware')
    op.drop_table('firmware')
    # ### end Alembic commands ###
