"""initial 4

Revision ID: 51bb9d8d8162
Revises: ab35d3c12316
Create Date: 2025-04-16 20:47:37.657002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bb9d8d8162'
down_revision: Union[str, None] = 'ab35d3c12316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_restaurant_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_restaurant_id_fkey', 'review', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
