"""update charge_chargeowner 2

Revision ID: 6eb0d2e5f24b
Revises: 0f983b90d246
Create Date: 2025-05-21 20:10:17.086620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb0d2e5f24b'
down_revision: Union[str, None] = '0f983b90d246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chargeowner', 'compagny',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chargeowner', 'compagny',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
