"""update device table

Revision ID: 6f9677509fc5
Revises: bab2ab29c842
Create Date: 2025-06-22 14:25:28.299013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9677509fc5'
down_revision: Union[str, None] = 'bab2ab29c842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('price_area', sa.String(length=10), nullable=True))
    op.add_column('device', sa.Column('config', sa.String(length=1000), nullable=True))
    op.add_column('device', sa.Column('is_adopted', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('adopted_at', sa.DateTime(), nullable=True))
    op.add_column('device', sa.Column('is_blocked', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    op.alter_column('device', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('device', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('device', 'PriceArea')
    op.drop_column('device', 'Config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('Config', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('PriceArea', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.alter_column('device', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('device', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('device', 'blocked_at')
    op.drop_column('device', 'is_blocked')
    op.drop_column('device', 'adopted_at')
    op.drop_column('device', 'is_adopted')
    op.drop_column('device', 'config')
    op.drop_column('device', 'price_area')
    # ### end Alembic commands ###
