"""initial 5

Revision ID: 8509b205dfdb
Revises: 51bb9d8d8162
Create Date: 2025-04-17 19:40:33.657323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8509b205dfdb'
down_revision: Union[str, None] = '51bb9d8d8162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'street_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('restaurant', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'review_text',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('review', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('review', 'review_text',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('restaurant', 'street_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
