"""firmwareupdate 2

Revision ID: 8b8452973cd5
Revises: 219ac7502bf2
Create Date: 2025-07-05 18:48:14.204044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8452973cd5'
down_revision: Union[str, None] = '219ac7502bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'firmware', 'devicetype', ['devicetype_id'], ['id'])
    op.create_foreign_key(None, 'hardware', 'devicetype', ['devicetype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hardware', type_='foreignkey')
    op.drop_constraint(None, 'firmware', type_='foreignkey')
    # ### end Alembic commands ###
