"""spotprice unique and index

Revision ID: bab2ab29c842
Revises: 6eb0d2e5f24b
Create Date: 2025-05-28 19:45:57.274486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab2ab29c842'
down_revision: Union[str, None] = '6eb0d2e5f24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_datedk_pricearea', 'spotprice', ['DateDK', 'PriceArea'], unique=False)
    op.create_unique_constraint('uq_hourdk_pricearea', 'spotprice', ['HourDK', 'PriceArea'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hourdk_pricearea', 'spotprice', type_='unique')
    op.drop_index('ix_datedk_pricearea', table_name='spotprice')
    # ### end Alembic commands ###
