"""Update user and device models

Revision ID: d83645122376
Revises: 0d662679cfa0
Create Date: 2025-05-17 19:02:00.940376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83645122376'
down_revision: Union[str, None] = '0d662679cfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'device', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_tokens_user_id_fkey', 'user_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.create_foreign_key('user_tokens_user_id_fkey', 'user_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'user_id')
    # ### end Alembic commands ###
